FILE(GLOB_RECURSE ALL_SOURCES
    "${CMAKE_SOURCE_DIR}/src/*.cpp"
    "${CMAKE_SOURCE_DIR}/utest/*.cpp"
)
FILE(GLOB_RECURSE ALL_HEADERS
    "${CMAKE_SOURCE_DIR}/src/*.hpp"
    "${CMAKE_SOURCE_DIR}/src/*.h"
    "${CMAKE_SOURCE_DIR}/utest/*.hpp"
    "${CMAKE_SOURCE_DIR}/utest/*.h"
)
SET(ALL_FILES
    ${ALL_SOURCES} ${ALL_HEADERS}
)


FILE(GLOB_RECURSE MAIN_SOURCES
    "${CMAKE_SOURCE_DIR}/src/*.cpp"
)
FILE(GLOB_RECURSE MAIN_HEADERS
    "${CMAKE_SOURCE_DIR}/src/*.hpp"
    "${CMAKE_SOURCE_DIR}/src/*.h"
)
SET(ALL_MAIN_FILES
    ${ALL_ANALIZE_SOURCES} ${ALL_ANALIZE_HEADERS}
)

SET(FILE_MAIN_CPP ${CMAKE_SOURCE_DIR}/src/main.cpp)
